### PR TITLE
docs: update notes on required permissions

### PR DESCRIPTION
**Pull request by MelkorNemesis**

### CODE REVIEW

**Review by simoneb — COMMENTED** [review]
Why did the dist output change?

**Comment by MelkorNemesis** [comment]
> Why did the dist output change?

I'm figuring that out now. I'm using the same node version as defined in `.nvmrc`. The build happens automatically after committing (husky).

**Comment by simoneb** [comment]
why don't you take the chance to also reflect the permissions in the workflow that uses this action itself, so we can see it working?

**Comment by MelkorNemesis** [comment]
> why don't you take the chance to also reflect the permissions in the workflow that uses this action itself, so we can see it working?

I think I did? https://github.com/nearform-actions/github-action-check-linked-issues/pull/281/files#diff-1f3207cbf76f88e35c70f67e100f794f61ba40c8fd8620d8589bb840ad98252d

But the trigger is `pull_request_target`, so it won't consider the workflow file in the pull request but the one in `main`?

**Comment by simoneb** [comment]
oh ok cool, usual issue I keep failing to see

**Review by simoneb — APPROVED** [review]

**Pull request merged**
