### PR TITLE
Change regex to accept both issue formats

### LINKED ISSUE #514: Does not recognize issues contained in outputs.issues
Szenario:
1. The action is used for checking the issue linked in the PR body when a PR is created on our beta branch. With `loose-matching: true`.
2. The PR is merged into beta and triggers another action which creates/updates a PR on master/main (default branch)
Therefore I use the action's outputs.issues to add close statements. The created PR body then contains:

```
The following issues will be closed after merging beta into the master with this PR:
Closes org-name/repo#1801 
Closes org-name/repo#1799 
Closes org-name/repo#1807 &#8203;
```

These close statements are not accepted by nearform-actions/github-action-check-linked-issues.

Used action to update the PR body:

```
name: Create/Update PR with linked issues to master from issues linked to merged PRs to beta

on:
  pull_request:
    types: [closed]
    branches:
      - beta

jobs:
  check_closed_issues_and_create_or_update_pr_to_master:
    name: Get linked issues and update PR
    runs-on: ubuntu-latest
    steps:
      - name: Get linked issues
        uses: nearform-actions/github-action-check-linked-issues@v1
        id: check-linked-issues
        with:
          exclude-branches: "release/**, dependabot/**"
          loose-matching: true
      - name: Print linked issues to console
        run: echo "${{ steps.check-linked-issues.outputs.issues }}"
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: GitHub Action for creating Pull Requests
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: beta
          target_branch: master
          title: New Prod Update
          body: "The following issues will be closed after merging beta into the master with this PR:&#8203;"
          old_string: "&#8203;"
          new_string: "\nCloses ${{ join(fromJSON(steps.check-linked-issues.outputs.issues), '\n Closes ') }} &#8203;"
          get_diff: true
          ignore_users: "dependabot"
          allow_no_diff: false
```

Would it be possible to also accept close statements with "org-name/repo/#issue-number" as this is the output of the action?

Otherwise, I have to change the action to change the outputs.issues to either #issue-number or link to issue.

### PR DESCRIPTION
**Pull request by alt-13**
Closes nearform-actions/github-action-check-linked-issues#514 &#8203;

Maybe not the most elegant way but my regex knowledge is limited.

Change regex to accept both issue formats:
closes https://github.com/org-name/repo/issues/123
closes org-name/repo#123

### CODE REVIEW

**Review by simoneb — CHANGES_REQUESTED** [review]
Can you please describe what format this supports? Also, please include unit tests

**Comment by alt-13** [comment]
PR body is: 
image

How else do you want to test this?
Unit test is already in place for getLinkedIssues

**Comment by simoneb** [comment]
check out the unit tests in the codebase, they can serve as a blueprint about what we are testing and want to test

**Comment by simoneb** [comment]
@alt-13 just a reminder to update/add tests please

**Comment by alt-13** [comment]
> @alt-13 just a reminder to update/add tests, please

I am sorry. I was unavailable last week. Please clarify if the output of the action should be seen as an external issue (owner/repo#123) as this format also can link to an external issue.

**Comment by simoneb** [comment]
Thanks for the follow up. Based on the [documentation](https://github.com/nearform-actions/github-action-check-linked-issues?tab=readme-ov-file#outputs), the current output seems to be in the form "some/repo#123". In hindsight maybe that should have been a url, but since this format supports both internal and external issues, I'd say we can easily keep this format to link any issue, whether internal or extenal. What do you think?

**Comment by alt-13** [comment]
Yes, I think so too.

So for me, it is ok as it is. I hope there is no codestyle issue anywhere.

**Comment by simoneb** [comment]
please fix the linting error. you can run linting locally before pushing. can you also please undo the formatting changes to the documentation?

**Comment by alt-13** [comment]
All requested changes applied. Is there anything else to fix?

**Review by simoneb — APPROVED** [review]

**Pull request merged**
